### ISSUE TITLE
Tracking spec level support

### ISSUE THREAD

**Issue by brianjmiller** [RusticiSoftware/TinCanJava#8]
Just opening this issue as clearing house for what is and isn't in yet towards spec compliance.

Requirements:
- [x] Bump version list
- [x] Context Activities as arrays
- [ ] deprecated 'voided'
- [x] Add Statement 'version' property
- [ ] Query API (authoritative removal, mode expansion)
- [x] Fetch voided statements
- [ ] Anonymous Groups
- [x] Document merge/partial updates (State, Activity Profile, Agent Profile)
- [x] Statement attachments
- [ ] Statement signing
- [ ] Fetch of URL related items
